<?php

namespace Database\Seeders;

use App\Models\BlogPost;
use App\Models\BlogPostTag;
use App\Models\BlogPostContentBlock;
use App\Models\TeamMember;
use Illuminate\Database\Seeder;

class BlogPostSeeder extends Seeder
{
    public function run(): void
    {
        $ceo = TeamMember::where('slug', 'md-rubayet-islam')->first();

        $posts = $this->getPosts();
        foreach ($posts as $i => $data) {
            $tags = $data['tags'] ?? [];
            $content = $data['content'] ?? [];
            unset($data['tags'], $data['content']);

            $data['author_team_member_id'] = $ceo?->id;
            $data['sort_order'] = $i;

            $post = BlogPost::create($data);

            foreach ($tags as $tag) {
                BlogPostTag::create(['blog_post_id' => $post->id, 'tag' => $tag]);
            }
            foreach ($content as $j => $block) {
                BlogPostContentBlock::create([
                    'blog_post_id' => $post->id,
                    'type' => $block['type'],
                    'content' => $block['type'] === 'list' ? $block['content'] : $block['content'],
                    'sort_order' => $j,
                ]);
            }
        }
    }

    private function getPosts(): array
    {
        return [
            // ── Web & App (5) ──
            ['slug'=>'react-server-components-practical-guide','title'=>'React Server Components: A Practical Guide for Production Apps','excerpt'=>'Understand how RSCs change the data-fetching paradigm, reduce client bundle size by up to 40%, and when to adopt them in real projects.','category'=>'Web & App','read_time'=>'10 min read','date'=>'Jan 15, 2025','image_url'=>'https://images.unsplash.com/photo-1633356122544-f134324a6cee?q=80&w=2070&auto=format&fit=crop','tags'=>['React','RSC','Next.js','Performance'],'content'=>[['type'=>'text','content'=>'React Server Components represent the most significant architectural shift in React since Hooks.'],['type'=>'heading','content'=>'What Are Server Components?'],['type'=>'text','content'=>'Server Components are React components that execute exclusively on the server.'],['type'=>'heading','content'=>'When Should You Adopt RSCs?'],['type'=>'text','content'=>'RSCs shine in data-heavy applications where large portions of the UI are read-only.'],['type'=>'quote','content'=>'The best JavaScript is no JavaScript. Server Components let you build rich UIs while shipping dramatically less code to the user.'],['type'=>'heading','content'=>'Practical Migration Strategy'],['type'=>'list','content'=>['Audit your component tree — identify purely presentational components','Convert leaf components that don\'t use hooks or browser APIs','Keep interactive components as Client Components','Use the "use client" directive only where interactivity is required','Measure bundle size before and after']],['type'=>'text','content'=>'At Boraq, we migrated a client dashboard from a fully client-rendered React SPA to an RSC-based architecture. The result was a 38% reduction in initial JavaScript payload.']]],
            ['slug'=>'flutter-vs-react-native-2025','title'=>'Flutter vs React Native in 2025: How We Choose for Client Projects','excerpt'=>'A transparent breakdown of how we evaluate cross-platform frameworks.','category'=>'Web & App','read_time'=>'8 min read','date'=>'Mar 05, 2025','image_url'=>'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?q=80&w=2070&auto=format&fit=crop','tags'=>['Flutter','React Native','Mobile','Cross-Platform'],'content'=>[['type'=>'text','content'=>'The cross-platform debate has matured significantly.'],['type'=>'heading','content'=>'Our Decision Framework'],['type'=>'text','content'=>'We evaluate five dimensions: UI complexity, native API depth, team familiarity, ecosystem maturity, and long-term maintenance cost.'],['type'=>'heading','content'=>'When We Choose Flutter'],['type'=>'list','content'=>['Pixel-perfect custom UI with heavy animations','Identical look across iOS and Android is critical','The team has Dart experience or the project is greenfield']],['type'=>'heading','content'=>'When We Choose React Native'],['type'=>'list','content'=>['Existing React web codebase to share logic with','Heavy reliance on native modules','The client team will maintain the app in-house']],['type'=>'quote','content'=>'The best framework is the one your team can ship and maintain confidently.']]],
            ['slug'=>'edge-first-architecture-nextjs-cloudflare','title'=>'Edge-First Architecture with Next.js and Cloudflare Workers','excerpt'=>'How deploying compute at the edge reduces latency by 60%.','category'=>'Web & App','read_time'=>'9 min read','date'=>'May 20, 2025','image_url'=>'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=2072&auto=format&fit=crop','tags'=>['Edge Computing','Next.js','Cloudflare','Performance'],'content'=>[['type'=>'text','content'=>'Traditional server architectures route every request to a single origin.'],['type'=>'heading','content'=>'The Edge Runtime Model'],['type'=>'text','content'=>'Cloudflare Workers run on V8 isolates across 300+ data centers worldwide.'],['type'=>'list','content'=>['Authentication and session validation','Geolocation-based content routing','A/B test assignment and feature flags']],['type'=>'quote','content'=>'The fastest request is the one that never leaves the continent.']]],
            ['slug'=>'monorepo-strategies-turborepo-nx','title'=>'Monorepo Strategies: Scaling Frontend Codebases with Turborepo & Nx','excerpt'=>'Lessons from managing 15+ packages in a single repository.','category'=>'Web & App','read_time'=>'7 min read','date'=>'Aug 12, 2025','image_url'=>'https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?q=80&w=2076&auto=format&fit=crop','tags'=>['Monorepo','Turborepo','Nx','DevOps'],'content'=>[['type'=>'text','content'=>'When you maintain a design system, three web apps, two mobile apps, and shared utility libraries, the polyrepo model becomes a coordination nightmare.'],['type'=>'heading','content'=>'Five Rules for Monorepo Success'],['type'=>'list','content'=>['Enforce strict package boundaries','Use remote caching','Define a clear ownership model','Keep shared packages small and focused','Automate changesets and versioning']],['type'=>'quote','content'=>'A monorepo without discipline is just a monolith wearing a trench coat.']]],
            ['slug'=>'progressive-web-apps-offline-first','title'=>'Offline-First PWAs: Building Apps That Work Without Internet','excerpt'=>'A comprehensive guide to service workers, Cache API strategies, and IndexedDB patterns.','category'=>'Web & App','read_time'=>'11 min read','date'=>'Nov 03, 2025','image_url'=>'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=2034&auto=format&fit=crop','tags'=>['PWA','Service Workers','Offline','IndexedDB'],'content'=>[['type'=>'text','content'=>'In Bangladesh, where 4G coverage is inconsistent, building web apps that assume constant connectivity is a design failure.'],['type'=>'heading','content'=>'Caching Strategies We Use'],['type'=>'list','content'=>['Cache First — for static assets','Network First — for API responses','Stale While Revalidate — for infrequent changes']],['type'=>'quote','content'=>'Offline-first isn\'t just a technical choice — it\'s an empathy-driven design philosophy.']]],

            // ── UI & Branding (5) ──
            ['slug'=>'building-design-systems-that-scale','title'=>'Building Design Systems That Scale Across 50+ Products','excerpt'=>'The architectural decisions that make a design system survive real-world adoption at scale.','category'=>'UI & Branding','read_time'=>'9 min read','date'=>'Feb 10, 2025','image_url'=>'https://images.unsplash.com/photo-1561070791-2526d30994b5?q=80&w=2000&auto=format&fit=crop','tags'=>['Design Systems','Component Libraries','Figma','Tokens'],'content'=>[['type'=>'text','content'=>'A design system isn\'t a component library. It\'s a living product.'],['type'=>'heading','content'=>'The Token-First Architecture'],['type'=>'text','content'=>'Design tokens are the atomic building blocks expressed as platform-agnostic JSON.'],['type'=>'heading','content'=>'Component API Design Principles'],['type'=>'list','content'=>['Composition over configuration','Sensible defaults with escape hatches','Controlled and uncontrolled patterns','Accessibility baked in']],['type'=>'quote','content'=>'The measure of a design system isn\'t how many components it has — it\'s how many components teams DON\'T have to build themselves.']]],
            ['slug'=>'motion-design-principles-modern-interfaces','title'=>'Motion Design Principles for Modern Web Interfaces','excerpt'=>'How purposeful animation improves usability and guides attention.','category'=>'UI & Branding','read_time'=>'7 min read','date'=>'Apr 18, 2025','image_url'=>'https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=2070&auto=format&fit=crop','tags'=>['Motion Design','Animation','Framer Motion','UX'],'content'=>[['type'=>'text','content'=>'Animation in UI design serves three purposes: feedback, context, and attention.'],['type'=>'heading','content'=>'The 200ms Rule'],['type'=>'text','content'=>'Research shows that animations between 150–300ms feel natural.'],['type'=>'quote','content'=>'Good animation is invisible. Users don\'t notice it — they just feel that the interface is polished.']]],
            ['slug'=>'accessible-design-beyond-wcag','title'=>'Accessible Design: Going Beyond WCAG Compliance','excerpt'=>'WCAG conformance is the floor, not the ceiling.','category'=>'UI & Branding','read_time'=>'8 min read','date'=>'Jul 22, 2025','image_url'=>'https://images.unsplash.com/photo-1573164713714-d95e436ab8d6?q=80&w=2069&auto=format&fit=crop','tags'=>['Accessibility','WCAG','Inclusive Design','A11y'],'content'=>[['type'=>'text','content'=>'Passing a WCAG audit doesn\'t mean your product is accessible.'],['type'=>'heading','content'=>'Our Accessibility Principles'],['type'=>'list','content'=>['48px minimum touch targets','Color is never the sole means of conveying information','Every element is keyboard-navigable']],['type'=>'quote','content'=>'Designing for accessibility doesn\'t limit creativity — it expands your audience.']]],
            ['slug'=>'psychology-of-color-in-saas-branding','title'=>'The Psychology of Color in SaaS Branding','excerpt'=>'Why 62% of SaaS products use blue and how to differentiate.','category'=>'UI & Branding','read_time'=>'6 min read','date'=>'Sep 30, 2025','image_url'=>'https://images.unsplash.com/photo-1525909002-1b05e0c869d8?q=80&w=2070&auto=format&fit=crop','tags'=>['Color Theory','Branding','SaaS','Psychology'],'content'=>[['type'=>'text','content'=>'Blue dominates SaaS branding because it signals trust, stability, and competence.'],['type'=>'heading','content'=>'The Boraq Teal Decision'],['type'=>'text','content'=>'When building the Boraq brand, we deliberately chose teal.'],['type'=>'quote','content'=>'Your brand color isn\'t just an aesthetic choice — it\'s a psychological signal.']]],
            ['slug'=>'figma-to-code-bridging-gap','title'=>'Figma to Code: Bridging the Design-Engineering Gap in 2025','excerpt'=>'Practical workflows for design-to-development handoff.','category'=>'UI & Branding','read_time'=>'8 min read','date'=>'Dec 08, 2025','image_url'=>'https://images.unsplash.com/photo-1581291518633-83b4eef1d2fa?q=80&w=2070&auto=format&fit=crop','tags'=>['Figma','Design Handoff','Dev Mode','Workflow'],'content'=>[['type'=>'text','content'=>'The design-to-code gap has been the source of friction between designers and developers since the dawn of digital products.'],['type'=>'heading','content'=>'Our Handoff Workflow'],['type'=>'list','content'=>['Design tokens synced via Tokens Studio','Components built with auto-layout matching CSS Flexbox','Storybook as the source of truth']],['type'=>'quote','content'=>'The best handoff is no handoff.']]],

            // ── AI & Automation (5) ──
            ['slug'=>'ai-agents-autonomous-workflows','title'=>'AI Agents: Building Autonomous Workflows for Enterprise','excerpt'=>'How multi-agent architectures are transforming business process automation.','category'=>'AI & Automation','read_time'=>'10 min read','date'=>'Feb 28, 2025','image_url'=>'https://images.unsplash.com/photo-1677442136019-21780ecad995?q=80&w=2070&auto=format&fit=crop','tags'=>['AI Agents','LLM','Automation','Enterprise'],'content'=>[['type'=>'text','content'=>'AI agents represent the next evolution beyond chatbots.'],['type'=>'heading','content'=>'Real-World Use Cases We\'ve Built'],['type'=>'list','content'=>['Customer support agent resolving 73% of tickets','Financial data analyst pulling from 5 APIs','Code review agent checking PRs']],['type'=>'quote','content'=>'The measure of an AI agent isn\'t how smart it is — it\'s how gracefully it handles the cases where it isn\'t smart enough.']]],
            ['slug'=>'rag-architecture-beyond-chatbots','title'=>'RAG Architecture: Beyond Chatbots to Knowledge Systems','excerpt'=>'Retrieval-Augmented Generation transforms LLMs into domain experts.','category'=>'AI & Automation','read_time'=>'9 min read','date'=>'May 15, 2025','image_url'=>'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?q=80&w=2065&auto=format&fit=crop','tags'=>['RAG','Vector Database','LLM','Knowledge Management'],'content'=>[['type'=>'text','content'=>'LLMs are remarkable at language understanding but unreliable at factual accuracy.'],['type'=>'heading','content'=>'Common RAG Pitfalls'],['type'=>'list','content'=>['Chunk size too large','Ignoring metadata filtering','Not reranking results']],['type'=>'quote','content'=>'RAG isn\'t just a technique — it\'s the bridge between an LLM\'s linguistic intelligence and your organization\'s domain knowledge.']]],
            ['slug'=>'fine-tuning-llms-domain-specific','title'=>'Fine-Tuning LLMs for Domain-Specific Business Applications','excerpt'=>'When RAG isn\'t enough — a guide to fine-tuning open-source LLMs.','category'=>'AI & Automation','read_time'=>'8 min read','date'=>'Jul 10, 2025','image_url'=>'https://images.unsplash.com/photo-1555255707-c07966088b7b?q=80&w=2036&auto=format&fit=crop','tags'=>['Fine-Tuning','LLM','LoRA','ML Ops'],'content'=>[['type'=>'text','content'=>'RAG excels at knowledge retrieval, but some tasks require learning a specific behavior pattern.'],['type'=>'heading','content'=>'The LoRA Advantage'],['type'=>'text','content'=>'Low-Rank Adaptation fine-tunes only a small number of additional parameters.'],['type'=>'quote','content'=>'The quality of your training data matters more than the size of your model.']]],
            ['slug'=>'automating-business-processes-langchain','title'=>'Automating Business Processes with LangChain and n8n','excerpt'=>'A practical playbook for connecting AI reasoning to real business workflows.','category'=>'AI & Automation','read_time'=>'7 min read','date'=>'Oct 05, 2025','image_url'=>'https://images.unsplash.com/photo-1518186285589-2f7649de83e0?q=80&w=2074&auto=format&fit=crop','tags'=>['LangChain','n8n','Workflow Automation','Integration'],'content'=>[['type'=>'text','content'=>'Most businesses run on a patchwork of manual processes.'],['type'=>'heading','content'=>'Five Workflows We Deploy Repeatedly'],['type'=>'list','content'=>['Inbound lead qualification','Invoice processing','Support ticket routing','Content repurposing','Meeting summarization']],['type'=>'quote','content'=>'Automation isn\'t about replacing humans — it\'s about freeing them from repetitive work.']]],
            ['slug'=>'responsible-ai-governance-startups','title'=>'Responsible AI: A Governance Framework for Startups','excerpt'=>'A pragmatic framework for teams of 5–50.','category'=>'AI & Automation','read_time'=>'7 min read','date'=>'Jan 20, 2026','image_url'=>'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=2070&auto=format&fit=crop','tags'=>['AI Ethics','Governance','Responsible AI','Compliance'],'content'=>[['type'=>'text','content'=>'AI governance sounds like something for Google and Microsoft to worry about. But if you\'re building products that make decisions affecting people, you have an obligation.'],['type'=>'heading','content'=>'The Lightweight Governance Framework'],['type'=>'list','content'=>['Risk Assessment','Data Documentation','Model Cards','Human-in-the-Loop','Monitoring']],['type'=>'quote','content'=>'Moving fast and breaking things is acceptable for features. It\'s unacceptable for systems that affect people\'s livelihoods.']]],

            // ── Vision & Speech (5) ──
            ['slug'=>'computer-vision-retail-inventory','title'=>'Computer Vision in Retail: Real-Time Inventory Management','excerpt'=>'How camera-based shelf monitoring with YOLO reduces out-of-stocks by 35%.','category'=>'Vision & Speech','read_time'=>'9 min read','date'=>'Mar 18, 2025','image_url'=>'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?q=80&w=2070&auto=format&fit=crop','tags'=>['Computer Vision','Retail','YOLO','Edge AI'],'content'=>[['type'=>'text','content'=>'Retail out-of-stocks cost the global industry $1.75 trillion annually.'],['type'=>'heading','content'=>'Challenges We Solved'],['type'=>'list','content'=>['Lighting variation','Occlusion','SKU similarity','Scale']],['type'=>'quote','content'=>'Computer vision doesn\'t just count products — it understands shelf context.']]],
            ['slug'=>'speech-to-text-multilingual-accuracy','title'=>'Achieving 99% Speech-to-Text Accuracy in Multilingual Applications','excerpt'=>'From Whisper fine-tuning to Bangla language models.','category'=>'Vision & Speech','read_time'=>'8 min read','date'=>'Jun 08, 2025','image_url'=>'https://images.unsplash.com/photo-1589254065878-42c9da997008?q=80&w=2070&auto=format&fit=crop','tags'=>['Speech-to-Text','Whisper','NLP','Bangla'],'content'=>[['type'=>'text','content'=>'OpenAI\'s Whisper model democratized speech recognition, but accuracy varies by language.'],['type'=>'heading','content'=>'Key Accuracy Improvements'],['type'=>'list','content'=>['Base Whisper on Bangla: 78.2% WER','After fine-tuning: 92.4% WER','With language model rescoring: 95.1% WER']],['type'=>'quote','content'=>'Speech recognition accuracy for low-resource languages isn\'t a technology problem — it\'s a data problem.']]],
            ['slug'=>'real-time-object-detection-edge-devices','title'=>'Real-Time Object Detection on Edge Devices with YOLO v10','excerpt'=>'Deploying 60fps object detection on a $200 device.','category'=>'Vision & Speech','read_time'=>'10 min read','date'=>'Aug 25, 2025','image_url'=>'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?q=80&w=2070&auto=format&fit=crop','tags'=>['Object Detection','YOLO','Edge AI','TensorRT'],'content'=>[['type'=>'text','content'=>'Cloud-based inference introduces latency and bandwidth costs unacceptable for real-time applications.'],['type'=>'heading','content'=>'Optimization Steps'],['type'=>'list','content'=>['Export PyTorch → ONNX','Convert ONNX → TensorRT with FP16','Optimize input pipeline with GStreamer']],['type'=>'quote','content'=>'The best AI model is the one that runs fast enough to be useful.']]],
            ['slug'=>'production-ocr-pipeline-documents','title'=>'Building a Production OCR Pipeline for Document Processing','excerpt'=>'From scanned PDFs to structured JSON.','category'=>'Vision & Speech','read_time'=>'8 min read','date'=>'Nov 15, 2025','image_url'=>'https://images.unsplash.com/photo-1568667256549-094345857637?q=80&w=2015&auto=format&fit=crop','tags'=>['OCR','Document AI','Tesseract','Production'],'content'=>[['type'=>'text','content'=>'Document processing is one of the highest-ROI applications of computer vision.'],['type'=>'heading','content'=>'Handling the Hard Cases'],['type'=>'list','content'=>['Handwritten text — fine-tuned TrOCR model','Tables — Camelot for bordered tables','Low-quality scans — adaptive thresholding']],['type'=>'quote','content'=>'OCR accuracy is a function of pre-processing quality.']]],
            ['slug'=>'emotion-recognition-ai-ethics','title'=>'Emotion Recognition AI: Ethical Boundaries and Practical Uses','excerpt'=>'The technology works — but should you use it?','category'=>'Vision & Speech','read_time'=>'7 min read','date'=>'Feb 05, 2026','image_url'=>'https://images.unsplash.com/photo-1531746790095-e5a41944f8ee?q=80&w=2006&auto=format&fit=crop','tags'=>['Emotion AI','Ethics','Facial Analysis','Consent'],'content'=>[['type'=>'text','content'=>'Emotion recognition technology can detect facial expressions, voice tone, and physiological signals.'],['type'=>'heading','content'=>'Where Emotion AI Is Defensible'],['type'=>'list','content'=>['Accessibility tools','Mental health monitoring','User research','Safety systems']],['type'=>'quote','content'=>'Technology capability should never outrun ethical consideration.']]],

            // ── Smart Device / IoT (5) ──
            ['slug'=>'iot-security-zero-trust','title'=>'IoT Security: Implementing Zero-Trust Architecture for Connected Devices','excerpt'=>'Why perimeter security fails for IoT.','category'=>'Smart Device','read_time'=>'9 min read','date'=>'Apr 10, 2025','image_url'=>'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?q=80&w=2070&auto=format&fit=crop','tags'=>['IoT Security','Zero Trust','mTLS','Device Identity'],'content'=>[['type'=>'text','content'=>'The average IoT device is breached within 5 minutes of connecting to the internet.'],['type'=>'heading','content'=>'Zero-Trust Principles for IoT'],['type'=>'list','content'=>['Device Identity','Mutual TLS','Least Privilege','Micro-Segmentation']],['type'=>'quote','content'=>'In IoT security, trust is not a state — it\'s a continuous verification process.']]],
            ['slug'=>'mqtt-vs-amqp-iot-messaging','title'=>'MQTT vs AMQP: Choosing the Right IoT Messaging Protocol','excerpt'=>'A practical comparison of the two dominant IoT messaging protocols.','category'=>'Smart Device','read_time'=>'7 min read','date'=>'Jun 25, 2025','image_url'=>'https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=2070&auto=format&fit=crop','tags'=>['MQTT','AMQP','IoT','Messaging'],'content'=>[['type'=>'text','content'=>'Messaging is the nervous system of any IoT architecture.'],['type'=>'heading','content'=>'Decision Matrix'],['type'=>'list','content'=>['Choose MQTT: constrained devices, low bandwidth','Choose AMQP: complex routing, enterprise integration']],['type'=>'quote','content'=>'The right protocol is the one that matches your constraints.']]],
            ['slug'=>'digital-twins-predictive-maintenance','title'=>'Digital Twins for Predictive Maintenance in Smart Factories','excerpt'=>'How real-time virtual replicas can predict failures 72 hours in advance.','category'=>'Smart Device','read_time'=>'8 min read','date'=>'Sep 14, 2025','image_url'=>'https://images.unsplash.com/photo-1565043666747-69f6646db940?q=80&w=2074&auto=format&fit=crop','tags'=>['Digital Twin','Predictive Maintenance','IIoT','Manufacturing'],'content'=>[['type'=>'text','content'=>'A digital twin is a real-time virtual replica of a physical asset.'],['type'=>'heading','content'=>'Predictive Maintenance ML Models'],['type'=>'list','content'=>['Vibration analysis','Temperature trending','Current signature analysis','Remaining Useful Life estimation']],['type'=>'quote','content'=>'Reactive maintenance costs 3x more than predictive maintenance.']]],
            ['slug'=>'smart-home-dashboard-raspberry-pi','title'=>'Building a Smart Home Dashboard with Raspberry Pi and React','excerpt'=>'A weekend project guide to building a touchscreen home automation dashboard.','category'=>'Smart Device','read_time'=>'10 min read','date'=>'Dec 01, 2025','image_url'=>'https://images.unsplash.com/photo-1558002038-1055907df827?q=80&w=2070&auto=format&fit=crop','tags'=>['Raspberry Pi','React','Smart Home','DIY IoT'],'content'=>[['type'=>'text','content'=>'Commercial smart home hubs cost $200–500 and lock you into proprietary ecosystems.'],['type'=>'heading','content'=>'Dashboard Features We Built'],['type'=>'list','content'=>['Real-time temperature and humidity','Smart plug control','Energy consumption tracking','Weather forecast integration']],['type'=>'quote','content'=>'The best smart home system is the one you control completely.']]],
            ['slug'=>'edge-computing-iot-reducing-cloud','title'=>'Edge Computing for IoT: Reducing Cloud Dependency by 80%','excerpt'=>'Why processing data at the edge cuts costs, improves latency.','category'=>'Smart Device','read_time'=>'8 min read','date'=>'Feb 20, 2026','image_url'=>'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?q=80&w=2070&auto=format&fit=crop','tags'=>['Edge Computing','IoT','Cost Optimization','Latency'],'content'=>[['type'=>'text','content'=>'The default IoT architecture sends every byte of sensor data to the cloud.'],['type'=>'heading','content'=>'What We Process at the Edge'],['type'=>'list','content'=>['Data aggregation','Threshold alerting','Anomaly detection','Data compression']],['type'=>'quote','content'=>'Not every data point deserves a cloud trip. Edge computing is about sending signals, not noise.']]],

            // ── Web3 (5) ──
            ['slug'=>'blockchain-scalability-layer2-rollups','title'=>'Blockchain Scalability: Layer-2 Rollups Explained for Developers','excerpt'=>'Optimistic vs ZK rollups — how Layer-2 solutions achieve 100x throughput.','category'=>'Web3','read_time'=>'9 min read','date'=>'Apr 28, 2025','image_url'=>'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?q=80&w=2070&auto=format&fit=crop','tags'=>['Layer 2','Rollups','Ethereum','Scalability'],'content'=>[['type'=>'text','content'=>'Ethereum\'s base layer processes 15–30 transactions per second.'],['type'=>'heading','content'=>'Decision Framework'],['type'=>'list','content'=>['Choose Optimistic: EVM compatibility, faster time-to-market','Choose ZK: fast withdrawals, privacy features']],['type'=>'quote','content'=>'Layer-2 isn\'t a compromise — it\'s the design.']]],
            ['slug'=>'building-dapps-solidity-hardhat','title'=>'Building Production dApps with Solidity and Hardhat','excerpt'=>'A battle-tested workflow for building decentralized applications.','category'=>'Web3','read_time'=>'10 min read','date'=>'Jul 05, 2025','image_url'=>'https://images.unsplash.com/photo-1642104704074-907c0698cbd9?q=80&w=2070&auto=format&fit=crop','tags'=>['Solidity','Hardhat','Smart Contracts','dApp'],'content'=>[['type'=>'text','content'=>'Building a production dApp is fundamentally different from traditional web development.'],['type'=>'heading','content'=>'Non-Negotiable Practices'],['type'=>'list','content'=>['100% test coverage','Fuzz testing with Foundry','Gas optimization','Multi-sig deployment']],['type'=>'quote','content'=>'In smart contract development, "move fast and break things" is how you lose $100 million.']]],
            ['slug'=>'tokenization-real-world-assets','title'=>'Tokenizing Real-World Assets: A Technical & Legal Guide','excerpt'=>'How blockchain-based tokenization is bringing real estate on-chain.','category'=>'Web3','read_time'=>'8 min read','date'=>'Sep 20, 2025','image_url'=>'https://images.unsplash.com/photo-1621761191319-c6fb62004040?q=80&w=2070&auto=format&fit=crop','tags'=>['RWA','Tokenization','DeFi','Regulation'],'content'=>[['type'=>'text','content'=>'Real-World Asset tokenization is the fastest-growing sector in crypto.'],['type'=>'heading','content'=>'Assets Being Tokenized'],['type'=>'list','content'=>['Real estate','US Treasury bonds','Private credit','Commodities','Carbon credits']],['type'=>'quote','content'=>'Tokenization doesn\'t just digitize assets — it democratizes access.']]],
            ['slug'=>'decentralized-identity-authentication','title'=>'Decentralized Identity (DID): The Future of Authentication','excerpt'=>'How self-sovereign identity eliminates passwords.','category'=>'Web3','read_time'=>'7 min read','date'=>'Dec 10, 2025','image_url'=>'https://images.unsplash.com/photo-1614064641938-3bbee52942c7?q=80&w=2070&auto=format&fit=crop','tags'=>['DID','Self-Sovereign Identity','Verifiable Credentials','Auth'],'content'=>[['type'=>'text','content'=>'The current identity model is broken.'],['type'=>'heading','content'=>'The Authentication Flow'],['type'=>'list','content'=>['User creates a DID and stores it in a wallet app','An issuer issues a Verifiable Credential','The credential is stored in the user\'s wallet']],['type'=>'quote','content'=>'Self-sovereign identity inverts the power dynamic.']]],
            ['slug'=>'smart-contract-security-audit-checklist','title'=>'Smart Contract Security: The Definitive Audit Checklist','excerpt'=>'The 25-point security checklist we use before every mainnet deployment.','category'=>'Web3','read_time'=>'11 min read','date'=>'Mar 01, 2026','image_url'=>'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?q=80&w=2070&auto=format&fit=crop','tags'=>['Security','Audit','Smart Contracts','Solidity'],'content'=>[['type'=>'text','content'=>'In 2024, over $1.8 billion was lost to smart contract exploits.'],['type'=>'heading','content'=>'Access Control & Authorization'],['type'=>'list','content'=>['All privileged functions have proper access modifiers','Multi-sig or timelock governance','No unprotected initializer functions']],['type'=>'quote','content'=>'Security auditing is not a one-time event — it\'s a continuous practice.']]],
        ];
    }
}

